### ISSUE TITLE
Generar un nivel de filtros en la busqueda.

### ISSUE THREAD

**Issue by Dave-JunDev** [Dave-JunDev/seacrh-gifs#2]
Que se pueda seleccionar la cantidad de gifs en pantalla, el tipo de gift y por fechas.

Es decir que sea posible generar un sistema de búsqueda más complejo permitiendo que el usuario lo pueda utilizar a su gusto y necesidad. 

--- Todos los cambios se realizaran en develop ---

**Comment by AndresFelipeAldana** [comment]
Se estima estiman 8 horas de esfuerzo para añadir una variable que controle las búsquedas tanto en fronet como backend
