### ISSUE TITLE
modificar filtro de la cantidad de gift en pantalla

### ISSUE THREAD

**Issue by Dave-JunDev** [Dave-JunDev/seacrh-gifs#3]
Así como en la historia anterior se busca que el mismo parámetro de la cantidad buscada sea el mismo que la cantidad que salgan en pantalla.

--- Todos los cambios se realizaran en develop ---

**Comment by CarlossAPB** [comment]
Se estima 1 hora de esfuerzo para implementar un filtro en el frontend que muestre la cantidad de gifs en pantalla que el usuario prefiera.

**Comment by CarlossAPB** [comment]
La variable que controla el número de items en pantalla se creó en el componente ListOfGifs. Quedo atento a la implementación del filtro que hará Andrés para que dicho filtro desde el frontend actualice el número de gifs que se traerán
