### ISSUE TITLE
Cambio de tema

### ISSUE THREAD

**Issue by Dave-JunDev** [Dave-JunDev/seacrh-gifs#5]
Se desea añadir una nueva funcionalidad que permita cambiar el tema de fondo del buscador de gift como de tema claro a oscuro, de momento solo se posee el tema oscuro

--- Todos los cambios se realizaran en develop ---

**Comment by CarlossAPB** [comment]
Se estima 1 hora de esfuerzo para implementar un botón con un icono Luna/Sol que permita realizar la alternancia de temas visuales.
